[package]
name = "renderer3d"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.28"
pixels = "0.13"
bytemuck = { version = "1.23.2", features = ["derive"] }
cgmath = "0.18.0"
pollster = "0.3"
